name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Setup Node.js 16.x
        uses: actions/setup-node@master
        with:
          registry-url: "https://registry.npmjs.org"
          node-version: 16.x

      - name: Install Dependencies
        run: yarn --immutable

      - run: yarn build

      - run: npx playwright install-deps

      - name: Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: yarn release
          commit: "ci(core): version packages"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Update yarn.lock
        run: |
          yarn --no-immutable
          status= git status

          if [[ "$status" == *"nothing to commit"* ]]; then
            git add yarn.lock
            git commit -m "chore: update dependencies"
            git push origin
          fi
